apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gyeongdodat-dev

resources:
  - ../../base

replicas:
  - name: gyeongdodat-front
    count: 1

images:
  - name: hub.klr.kr/gyeongdodat_front
    newTag: develop
