apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gyeongdodot-ingress
  namespace: gyeongdodot-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dev.gyeongdodot.klr.kr
    - api.dev.gyeongdodot.klr.kr
    secretName: gyeongdodot-dev-tls
  rules:
  - host: dev.gyeongdodot.klr.kr
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gyeongdodot-front
              port:
                number: 80
  - host: api.dev.gyeongdodot.klr.kr
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gyeongdodot-back
              port:
                number: 8080
