apiVersion: v1
kind: Service
metadata:
  name: gyeongdodot-front
  namespace: gyeongdodot
spec:
  selector:
    app: gyeongdodot-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
