apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gyeongdodot-dev

resources:
  - ../../base

replicas:
  - name: gyeongdodot-front
    count: 1

images:
  - name: hub.klr.kr/gyeongdodot_front
    newTag: develop
