apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gyeongdodot
resources:
  - ../../base
replicas:
  - name: gyeongdodot-back
    count: 2
images:
  - name: hub.klr.kr/gyeongdodot_back
    newTag: daef27c-1
