apiVersion: apps/v1
kind: Deployment
metadata:
  name: gyeongdodot-back
  namespace: gyeongdodot
  labels:
    app: gyeongdodot-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gyeongdodot-back
  template:
    metadata:
      labels:
        app: gyeongdodot-back
    spec:
      containers:
      - name: gyeongdodot-back
        image: hub.klr.kr/gyeongdodot_back:latest
        ports:
        - containerPort: 8080
