apiVersion: apps/v1
kind: Deployment
metadata:
  name: gyeongdodot-back
  labels:
    app: gyeongdodot-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gyeongdodot-back
  template:
    metadata:
      labels:
        app: gyeongdodot-back
    spec:
      containers:
      - name: gyeongdodot-back
        image: hub.klr.kr/gyeongdodot_back:latest
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATA_REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: gyeongdodot-redis
                key: SPRING_DATA_REDIS_HOST
          - name: SPRING_DATA_REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gyeongdodot-redis
                key: SPRING_DATA_REDIS_PASSWORD
