apiVersion: apps/v1
kind: Deployment
metadata:
  name: gyeongdodat-front
  labels:
    app: gyeongdodat-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gyeongdodat-front
  template:
    metadata:
      labels:
        app: gyeongdodat-front
    spec:
      containers:
      - name: gyeongdodat-front
        image: hub.klr.kr/gyeongdodat_front:latest
        ports:
        - containerPort: 80
